use UNIVER

select AUDITORIUM.AUDITORIUM_NAME, AUDITORIUM.AUDITORIUM_TYPE,AUDITORIUM_TYPE.AUDITORIUM_TYPENAME
from AUDITORIUM inner join AUDITORIUM_TYPE on AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE


select AUDITORIUM.AUDITORIUM_NAME, AUDITORIUM.AUDITORIUM_TYPE,AUDITORIUM_TYPE.AUDITORIUM_TYPENAME
from AUDITORIUM inner join AUDITORIUM_TYPE on AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE where AUDITORIUM_TYPE.AUDITORIUM_TYPENAME like '%компьютер%'

--задание 1,2
